version: '3.5'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-storage:/data
#    networks:
#      - portainer-net

volumes:
  portainer-storage:
    driver: local

#networks:
#  portainer-net:
#    external:
#      name: net_172_15
