version: '3'

services:

  consul:
    container_name: consul
    image: consul
    restart: always
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    volumes:
      - consul-storage:/consul/data

volumes:
  consul-storage:
    driver: local