version: '3.5'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
       - /home/iv4nlop3z/Documents/local-storage/mysql:/var/lib/mysql
