version: '3.2'

services:
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:6.5.1
    restart: always
    user: root
    volumes:
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - LOGSTASH_HOST=172.16.1.121:5044
    networks:
      - filebeat-net

networks:
  filebeat-net:
    external:
      name: net_172_15