version: '3.7'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  rancher:
    image: rancher/rancher
    restart: always
    privileged: true
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: rancher.example.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: rancher.example.com
      LETSENCRYPT_EMAIL: ivan@example.com

volumes:
  certs:
  confd:
  vhostd:
  html:
