version: "2"

services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-storage:/data/db

volumes:
  mongo-storage:
    driver: local