version: "2"

services:
  mysqldb:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-storage:/var/lib/mysql

volumes:
  mysql-storage:
    driver: local