version: "3.1"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mariadb-storage:/var/lib/mysql
    networks:
      - mariadb-net

networks:
  mariadb-net:
    external:
      name: net_172_15

volumes:
  mariadb-storage:
    driver: local